definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

pipelines:
  pull-requests:
    'main':
         - step:
            name: Build and test
            image: node:20.16.0
            script:
              - corepack enable
              - corepack prepare pnpm@latest --activate
              - pnpm install
              - pnpm run test
            caches:
              - pnpm
    'release':
         - step:
            name: Build and test
            image: node:20.16.0
            script:
              - corepack enable
              - corepack prepare pnpm@latest --activate
              - pnpm install
              - pnpm run test
            caches:
              - pnpm
    'development':
         - step:
            name: Build and test
            image: node:20.16.0
            script:
              - corepack enable
              - corepack prepare pnpm@latest --activate
              - pnpm install
              - pnpm run test
            caches:
              - pnpm
    'staging':
         - step:
            name: Build and test
            image: node:20.16.0
            script:
              - corepack enable
              - corepack prepare pnpm@latest --activate
              - pnpm install
              - pnpm run test
            caches:
              - pnpm